name: simplechat
base: core20
version: '0.1'
summary: simplechat backend service
description: |
  simplechat backend service

grade: devel
confinement: classic

apps:
  simplechat:
    daemon: simple
    restart-condition: on-failure
    command: bin/node $SNAP/lib/node_modules/simplechat/dist/index.js
    plugs:
      - network
      - network-bind

parts:
  simplechat:
    plugin: npm
    npm-node-version: 16.14.0
    source-type: local
    source: .
    build-snaps:
      - node/16/stable

environment:
  LD_LIBRARY_PATH: $SNAP/usr/local/lib/:$SNAP/usr/local/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
  DISABLE_WAYLAND: 1
  PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/usr/lib/python2.7/dist-packages/:$PYTHONPATH
